/**
 *
 *              MATH NEEDED TO LEARN PROGRAMMING
 * 1. NUMBER : POSITIVE NEGATIVE ZERO [10, -6, 0]
 * 2. INTEGER : 2, 88[ODD, EVEN]
 * 3. FLOAT : 4.6, 4.66
 * 4. OPERATION : SUMATION , SUBSTRACTION, MULTIPLICATION, DIVITION
 * 5. MORE OPERATION : % VAGSESH...REMAINER
 * 6. PERCENTAGE : 5%, 10%
 * 7. SUMMATION
 * 8. AVERAGE
 * 9. OIKIN NIYOM AND SO ON
 * 10. MAX AND MIN NUMBERS
 * 11. SERIES: DHARA
 * 12. AREA: TRIANGLE, RECTANGLE, POLYGON ETC.
 * 13. CHART AND GRAPH,
 * 14. AXIX [X AXIX , Y AXIX, AXIX]
 * 15.
 */
